name: Component Triggering
on: issue_comment
jobs:
  trigger-webhook:
    runs-on: ubuntu-latest
    steps:
      - uses: joelwmale/webhook-action@master
        with:
          url: 'https://gpuci.gpuopenanalytics.com/generic-webhook-trigger/invoke'
          headers: '{"token": "${{ secrets.WEBHOOK_TOKEN }}"}'
          body: '{"pr_id": "${{ github.event.issue.id }}". "sha": "${{ github.sha }}"}'
