name: Component Triggering
on: 
  issue_comment:
    types:
      - created
jobs:
  trigger-webhook:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - uses: joelwmale/webhook-action@master
        with:
          url: 'https://gpuci.gpuopenanalytics.com/generic-webhook-trigger/invoke'
          headers: '{"token": "${{ secrets.WEBHOOK_TOKEN }}"}'
          body: |
            {
            "pr_id": "${{ github.event.issue.number }}",
            "commit_hash": "pull/${{ github.event.issue.number }}/merge",
            "report_hash": "pull/${{ github.event.issue.number }}/head",
            "pr_author": "${{ github.event.issue.user.login }}",
            "source_branch": "${{ github.event.issue.head.ref }}",
            "target_branch": "${{ github.event.issue.base.ref }}",
            "flash_id": "${{ github.event.issue.number }}",
            "repository": "${{ github.event.repository.full_name }}"
            }
